spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client
  cloud:
    stream:
      kafka:
        binder:
          brokers: 101.200.216.156    

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7301/eureka

info:
  app.name: microconfig-test-client11122222
  company.name: gsnggggg
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client
  cloud:
    stream:
      kafka:
        binder:
          brokers: 101.200.216.156    

eureka:
 client:
  service-url:
    defaultZone: http://admin:a@localhost:7301/eureka
info:
  app.name: microconfig-test-client
  company.name: gsn
