spring:
  profiles:
    active:
      - dev
---
server:
 port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL   #配置主键自动增长
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Asd8711341
    url: jdbc:mysql://101.200.216.156:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  application:
    name: microservice-config-product-client
  profiles: dev

logging:
  level:
    com.gsn.springcloud1_2: debug
    org.springframework.security: debug

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:a@localhost:7001/eureka      #注意: dev环境下  eureka的端口要与前面的eureka的配置保持统一，这里是 7001
  instance:
    instance-id: microservice-config-product-client
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）
info:
  app.name: microservice-config-product-client
  company.name: gsn
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  build.version: $project.version$
  jdk.version: $java.version$  

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
---
server:
  port: 8888
spring:
  #security:
  # user:
  #   name: admin
  #  password: a
  # roles:
  #  - USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Asd8711341
    url: jdbc:mysql://101.200.216.156:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  application:
    name: microservice-provider
  profiles: beta  
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.gsn.springcloud1_2: debug
    org.springframework.security: debug
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #defaultZone: http://admin:a@localhost:7001/eureka  #授信用户登录
      defaultZone: http://admin:a@eureka2:7002/eureka
  instance:
    instance-id: microservice-provider-product_1   #实例名
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )
#监控配置
info:
  app.name: MICROSERVICE-PROVIDER
  company.name: gsn
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
  build.version: $project.version$
  jdk.version: $java.version$


management:
  endpoints:
    web:
      exposure:
        include: '*'
